# vim: set ft=sh :

# Fix weird chain-shell issues
# [ -z "${ZSH}" ] && export ZSH=$(find -O3 ~/.local -type l -user $USER -executable -name zsh 2>/dev/null | grep "bin" )
# export SHELL="$ZSH"
# export shell_name=zsh
# make all configs be in right place
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
# make zsh configs be in the right place
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export ZPLUG_HOME="$ZDOTDIR/zplug"

# fix xdg runtime dir making sway need a relaunch
# export XDG_RUNTIME_DIR=/run/user/1000
# doas -n mkdir -p $XDG_RUNTIME_DIR

# random exports for various quality-of-life things
export LANG="en_US.UTF-8"                                   # these two lines are
export LC_COLLATE="C"                                       # for silencing perl scripts
export MANPAGER="nvim +Man!"                                # Nvim does manpages...
export BAT_THEME="base16"                                   # Don't really use bat
export EDITOR="nvim"                                        # if you need this explained there is no hope
export GHCUP_USE_XDG_DIRS="anything"                        # clean up HOME

# work on fonts/scaling/haxx etc
export QT_QPA_PLATFORMTHEME="gtk2"  # Have QT use gtk2 theme.
export MOZ_USE_XINPUT2="1"          # smooth scrolling in FF
export WINIT_HIDPI_FACTOR="1.0"     # fix alacritty giant fonts on X
export WINIT_X11_SCALE_FACTOR="1.0" # fix alacritty giant fonts on X
export NEOVIDE_MULTIGRID="yeah"     # smooth scrolling etc in neovide
export XKB_DEFAULT_LAYOUT="us"
export XKB_DEFAULT_OPTS="custom:super_esc"

# my exports
export GNUPGHOME="$XDG_CONFIG_HOME/gnupg"
# see: npm config ls -l | grep /
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/config
export NPM_CONFIG_CACHE=$XDG_CACHE_HOME/npm
export NPM_CONFIG_TMP=$XDG_RUNTIME_DIR/npm
# Luke Smith's exports
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
export NOTMUCH_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/notmuch-config"
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"
export LESSHISTFILE="${XDG_CACHE_HOME:-$HOME/.cache}/less-history"
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"
export PASSWORD_STORE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/password-store"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export ANDROID_SDK_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/android"
export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"
export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
export ANSIBLE_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/ansible/ansible.cfg"
export UNISON="${XDG_DATA_HOME:-$HOME/.local/share}/unison"
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"
export MBSYNCRC="${XDG_CONFIG_HOME:-$HOME/.config}/mbsync/config"
export ELECTRUMDIR="${XDG_DATA_HOME:-$HOME/.local/share}/electrum"

# add personal bin folder and emacs functions to path, for custom scripts
export PATH=~/.local/bin:$PATH:~/.local/share/cargo/bin:~/.local/share/brew/bin:~/.local/share/brew/sbin

# Fix duplicate entries in PATH variable caused by sourcing this file multiple times
# source ~/.local/bin/fixpath
