# vim: set ft=sh :

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export ZPLUG_HOME="$ZDOTDIR/zplug"

export LANG="en_US.UTF-8"
export LC_COLLATE="C"

export MANPAGER="nvim +Man!"

export EDITOR="nvim"

export BAT_THEME="base16"
export QT_QPA_PLATFORMTHEME="gtk2"
export NEOVIDE_MULTIGRID="yeah"

export XKB_DEFAULT_LAYOUT="us"
export XKB_DEFAULT_OPTS="custom:super_esc"

export MOZ_USE_XINPUT2="1"
export WINIT_HIDPI_FACTOR="1.0"
export WINIT_X11_SCALE_FACTOR="1.0"

export GHCUP_USE_XDG_DIRS="anything"

export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/config
export NPM_CONFIG_CACHE=$XDG_CACHE_HOME/npm
export NPM_CONFIG_TMP=$XDG_RUNTIME_DIR/npm

export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"

export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"

export GNUPGHOME="$XDG_CONFIG_HOME/gnupg"
export PASSWORD_STORE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/password-store"

export ANDROID_SDK_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/android"

export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"

export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"

# export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"

export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"

export LESSHISTFILE="${XDG_CACHE_HOME:-$HOME/.cache}/less-history"

export TMUX_TMPDIR="$XDG_RUNTIME_DIR"

export PATH=/opt/local/bin:/opt/local/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:~/.local/bin:$PATH:~/.local/share/cargo/bin:~/.local/share/brew/bin:~/.local/share/brew/sbin
